import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Activity, Utensils, Dumbbell, TrendingUp, Download, Smartphone } from "lucide-react";
import { useIsMobile } from "../hooks/use-mobile";
import { usePwa } from "@/hooks/use-pwa";

export default function LandingPage() {
  const [splashVisible, setSplashVisible] = useState(true);
  const [, setLocation] = useLocation();
  const isMobile = useIsMobile();
  const { canInstall, isStandalone, install } = usePwa();
  const [showIOSInstructions, setShowIOSInstructions] = useState(false);
  
  // Check if the device is iOS
  const isIOS = typeof navigator !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent) && !(window as any).MSStream;

  // Effect to hide splash screen after delay
  useEffect(() => {
    if (splashVisible) {
      const timer = setTimeout(() => {
        setSplashVisible(false);
      }, 2500); // 2.5 seconds delay
      
      return () => clearTimeout(timer);
    }
  }, [splashVisible]);
  
  // Function to handle app installation
  const handleInstall = async () => {
    if (isIOS) {
      // iOS needs special instructions
      setShowIOSInstructions(true);
    } else {
      // For other platforms, use the install API
      const installed = await install();
      if (installed) {
        console.log('App installed successfully');
      }
    }
  };

  return (
    <>
      {/* Splash Screen */}
      {splashVisible && (
        <div className="fixed inset-0 z-50 flex items-center justify-center overflow-hidden" 
          style={{ 
            background: 'linear-gradient(135deg, #1a365d 0%, #2b6cb0 100%)'
          }}
        >
          <div className="absolute inset-0 opacity-15">
            <div className="absolute top-0 left-0 w-full h-64 bg-white/5 transform -skew-y-6"></div>
            <div className="absolute bottom-0 right-0 w-full h-64 bg-white/5 transform skew-y-6"></div>
          </div>
          <div className="flex flex-col items-center relative">
            <div className="flex items-center bg-white/10 backdrop-blur-sm px-8 py-6 rounded-2xl shadow-2xl mb-4">
              <Dumbbell className="h-10 w-10 text-blue-200 mr-3" />
              <h1 className="text-3xl font-bold text-white tracking-tight">TrackMadeEazE</h1>
            </div>
            <div className="relative mt-2">
              <div className="h-1 w-36 bg-blue-300/30 rounded-full overflow-hidden">
                <div className="h-1 bg-blue-200 rounded-full animate-load-progress"></div>
              </div>
              <p className="text-blue-200 text-sm mt-2 text-center font-medium">Personalizing your experience...</p>
            </div>
          </div>
        </div>
      )}
      
      <div 
        className={`min-h-screen flex flex-col transition-opacity duration-500 ${splashVisible ? 'opacity-0' : 'opacity-100'}`}
        style={{
          background: 'linear-gradient(135deg, #1a365d 0%, #2b6cb0 100%)',
        }}
      >
        <div className="flex-1 flex flex-col p-6 md:p-12">
          {/* Logo and App Name */}
          <div className="flex items-center mb-8">
            <Activity className="h-10 w-10 text-white mr-3" />
            <h1 className="text-3xl md:text-4xl font-bold text-white">TrackMadeEazE</h1>
          </div>
          
          {/* Main Headline */}
          <div className="mb-8">
            <h2 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-6">
              Your AI Personal Trainer, <span className="text-blue-200">wherever you go</span>
            </h2>
            <p className="text-xl text-white/90 max-w-2xl mb-3">
              A comprehensive fitness tracking application powered by AI to create personalized 
              workout plans and nutrition guidance tailored to your unique goals.
            </p>
            <div className="flex items-center">
              <div className="bg-blue-500/20 rounded-lg py-1 px-3 text-white text-sm flex items-center">
                <span className="mr-2">Powered by our proprietary TrackMadeEazE AI</span>
                <Activity className="h-3.5 w-3.5" />
              </div>
            </div>
          </div>
          
          {/* Feature List */}
          <div className="space-y-6 mb-12">
            <div className="flex items-start bg-blue-500/30 p-4 rounded-lg mb-2">
              <div className="h-10 w-10 flex items-center justify-center bg-blue-500 rounded-lg text-white mr-4 flex-shrink-0">
                <Activity className="h-6 w-6" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-white mb-1">AI Personal Trainer</h3>
                <p className="text-white/90">
                  Get personalized workout and nutrition plans generated by our proprietary AI, tailored to your specific goals, fitness level, and preferences
                </p>
              </div>
            </div>
            
            <div className="flex items-start">
              <Utensils className="h-7 w-7 text-white/90 mt-1 mr-4 flex-shrink-0" />
              <div>
                <h3 className="text-xl font-semibold text-white mb-1">Nutrition Tracking</h3>
                <p className="text-white/80">
                  Monitor your calories, protein, carbs, and fat intake with accurate information
                </p>
              </div>
            </div>
            
            <div className="flex items-start">
              <Dumbbell className="h-7 w-7 text-white/90 mt-1 mr-4 flex-shrink-0" />
              <div>
                <h3 className="text-xl font-semibold text-white mb-1">Workout Monitoring</h3>
                <p className="text-white/80">
                  Track all your exercises, sets, reps, and weights with easy-to-use interfaces
                </p>
              </div>
            </div>
            
            <div className="flex items-start">
              <TrendingUp className="h-7 w-7 text-white/90 mt-1 mr-4 flex-shrink-0" />
              <div>
                <h3 className="text-xl font-semibold text-white mb-1">Progress Tracking</h3>
                <p className="text-white/80">
                  View your improvements over time with detailed charts and analytics
                </p>
              </div>
            </div>
          </div>
          
          {/* CTA Buttons */}
          <div className="mt-auto flex flex-col md:flex-row gap-4">
            <Button 
              size="lg"
              className="w-full md:w-auto bg-white text-blue-600 hover:bg-blue-50 text-lg font-semibold py-7 px-8 h-auto rounded-xl shadow-lg transform transition duration-300 hover:scale-105 hover:shadow-xl"
              onClick={() => setLocation("/auth")}
            >
              <div className="flex items-center justify-center">
                <Dumbbell className="h-5 w-5 mr-2" />
                <span>I want to be fitter</span>
              </div>
            </Button>
            
            {/* Show install button if app can be installed and is not already in standalone mode */}
            {(canInstall || isIOS) && !isStandalone && (
              <Button 
                size="lg"
                className="w-full md:w-auto bg-blue-500 text-white hover:bg-blue-600 text-lg font-semibold py-7 px-8 h-auto rounded-xl shadow-lg"
                onClick={handleInstall}
              >
                <div className="flex items-center justify-center">
                  <Download className="h-5 w-5 mr-2" />
                  <span>Install App</span>
                </div>
              </Button>
            )}
          </div>
          
          {/* Extra Install Button for better visibility */}
          {(canInstall || isIOS) && !isStandalone && (
            <div className="mt-6 flex justify-center">
              <div className="bg-blue-100/30 backdrop-blur-sm rounded-xl p-4 flex items-center gap-3 max-w-md">
                <Smartphone className="h-8 w-8 text-white flex-shrink-0" />
                <div className="flex-1">
                  <p className="text-white/90 font-medium mb-1">Experience the full app</p>
                  <p className="text-white/80 text-sm">Install TrackMadeEazE on your device for the best experience with offline capabilities.</p>
                </div>
                <Button 
                  onClick={handleInstall}
                  className="flex-shrink-0 bg-white text-blue-600 hover:bg-blue-50"
                >
                  <Download className="h-4 w-4 mr-1.5" />
                  Install
                </Button>
              </div>
            </div>
          )}
          
          {/* iOS Install Instructions Modal */}
          {showIOSInstructions && (
            <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
              <div className="bg-white rounded-xl shadow-2xl max-w-md w-full overflow-hidden">
                <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-4 flex justify-between items-center">
                  <h3 className="font-bold text-xl text-white flex items-center">
                    <Smartphone className="w-5 h-5 mr-2" />
                    Install on iPhone
                  </h3>
                  <Button 
                    variant="ghost" 
                    size="icon" 
                    className="text-white hover:bg-white/20" 
                    onClick={() => setShowIOSInstructions(false)}
                  >
                    <span className="sr-only">Close</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                  </Button>
                </div>
                
                <div className="p-6 space-y-4">
                  <p className="text-center font-medium text-gray-700">Follow these steps to install TrackMadeEazE:</p>
                  
                  <div className="bg-gray-50 rounded-lg p-4 flex items-start border border-gray-200">
                    <div className="bg-blue-100 rounded-full h-8 w-8 flex items-center justify-center text-blue-600 font-bold mr-3 flex-shrink-0">1</div>
                    <div>
                      <p className="font-medium text-gray-800">Tap the Share button</p>
                      <p className="text-gray-600 text-sm">Tap the <span className="inline-block w-5 h-5 bg-blue-500 text-white rounded text-center leading-5">⬆</span> button at the bottom of your screen</p>
                    </div>
                  </div>
                  
                  <div className="bg-gray-50 rounded-lg p-4 flex items-start border border-gray-200">
                    <div className="bg-blue-100 rounded-full h-8 w-8 flex items-center justify-center text-blue-600 font-bold mr-3 flex-shrink-0">2</div>
                    <div>
                      <p className="font-medium text-gray-800">Scroll and tap Add to Home Screen</p>
                      <p className="text-gray-600 text-sm">You may need to scroll down to find this option</p>
                    </div>
                  </div>
                  
                  <div className="bg-gray-50 rounded-lg p-4 flex items-start border border-gray-200">
                    <div className="bg-blue-100 rounded-full h-8 w-8 flex items-center justify-center text-blue-600 font-bold mr-3 flex-shrink-0">3</div>
                    <div>
                      <p className="font-medium text-gray-800">Tap Add</p>
                      <p className="text-gray-600 text-sm">Look for the Add button in the top-right corner</p>
                    </div>
                  </div>
                  
                  <p className="text-center text-sm text-gray-500 italic">
                    You'll get the full app experience with offline capabilities!
                  </p>
                  
                  <div className="pt-2 flex justify-end">
                    <Button onClick={() => setShowIOSInstructions(false)}>Got it</Button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}